export const POSTS = [
  {
    _id: "1",
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: "/avatars/anju.avif",
    user: {
      fullName: "Anju Kumari",
      username: "anju_12",
      profileImg: "/avatars/anju.avif",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          fullName: "Avinash Pandey",
          username: "avi2492",
          profileImg: "/avatars/avinash.avif",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "How you guys doing? 😊",
    user: {
      fullName: "Avinash Pandey",
      username: "avi2492",
      profileImg: "/avatars/avinash.avif",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          fullName: "Simran Sinha",
          username: "simran.sinha",
          profileImg: "/avatars/simran.avif",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
    img: "/avatars/deepti.avif",
    user: {
      fullName: "Deepti Suman",
      username: "itsdeepti",
      profileImg: "/avatars/deepti.avif",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "I'm learning GO this week. Any tips? 🤔",
    img: "/avatars/simran.avif",
    user: {
      fullName: "Simran Sinha",
      username: "simran.sinha",
      profileImg: "/avatars/simran.avif",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          fullName: "Avinash Pandey",
          username: "avi2492",
          profileImg: "/avatars/avinash.avif",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "Anju Kumari",
    username: "anju_12",
    profileImg: "/avatars/anju.avif",
  },
  {
    _id: "2",
    fullName: "Avinash Pandey",
    username: "avi2492",
    profileImg: "/avatars/avinash.avif",
  },

  {
    _id: "3",
    fullName: "Deepti Suman",
    username: "itsdeepti",
    profileImg: "/avatars/deepti.avif",
  },
  {
    _id: "4",
    fullName: "Simran Sinha",
    username: "simran.sinha",
    profileImg: "/avatars/simran.avif",
  },
  {
    _id: "5",
    fullName: "Yashpal Singh",
    username: "yashpal.singh",
    profileImg: "/avatars/yashpal.avif",
  },
  {
    _id: "6",
    fullName: "Akash Singh",
    username: "akash_singh",
    profileImg: "/avatars/akash.avif",
  },
  {
    _id: "7",
    fullName: "Abhijeet Kumar",
    username: "itsabhi",
    profileImg: "/avatars/abhijeet.avif",
  },
];
